name: Demo .NET 8 API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build CatalogApi Docker image
      run: docker build . --file src/CatalogApi/Dockerfile --tag catalogapi:$(date +%s)

    - uses: actions/checkout@v4
    - name: Build the Auth Api image
      run: docker build . --file src/AuthApi/Dockerfile --tag authapi:$(date +%s)
    
